---
title: "SST timeseries"
author: "Dana K Briscoe"
date: '`r Sys.Date()`'
output: html_document
params:
  node: "pacioos" 
  url: "https://pae-paha.pacioos.hawaii.edu/erddap/griddap/"
  eov: "sst"
  varname: "CRW_SST"
  dataset_ID: "dhw_5km"
  enddate: !r Sys.Date() - 2
  startdate: !r params$enddate - 30
  timestep: "daily"
  nc_path: "/Users/briscoedk/dbriscoe@stanford.edu - Google Drive/My Drive/ncdf/deploy_reports"
  bbox: !r tibble::tibble(ymin=20, ymax=50,xmin=-180, xmax=-110)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    eval = TRUE,
    message = FALSE,
    warning = FALSE,
    dpi = 300,
    fig.align = "center",
    fig.height = 9
    )

# See Options: knitr::opts_chunk$get()
```


```{r load-libraries}
# Load Libraries ---
# library(RNetCDF)
library(tidyverse)
library(ncdf4)
library(lubridate)

```

```{r source-helper-funcs}
## Source helper functions
source('00_automate_SST_helper_functions.R')
```

```{r set-timeout-length}
options(timeout=360)
```

```{r load-ncdf-list}
eov_list <- jsonlite::read_json("../ncdf_list.json") %>%
                data.table::rbindlist(., fill=TRUE) %>% 
                # unnest(eov) %>%  
                purrr::pmap_dfr(data.frame)  # deals with remaining cols in list form


```

```{r}
params_df <- eov_list[eov_list$eov == params$eov & eov_list$timestep == params$timestep,]
```

```{r set-dateRange}
dates <- getDateRange(startdate = params$startdate,enddate = params$enddate, unit=params$timestep) %>%
    str_c(., unique(params_df$date_string), sep="")
```


```{r get-ncdfs}
for (i in 1:length(dates)) {
  tryCatch({
    getNCDF(
    url = params_df$url,
    eov = params_df$eov,
    varname = params_df$varname,
    dataset_ID = params_df$dataset_ID, 
    bbox = params$bbox, 
    dt = dates[i], 
    ncpath = params$nc_path
  )
  }, error = function(e){
      message('Caught an error!')
      print(e)
  }
  )
}
```

